### ISSUE TITLE
你好,请问为什么actionQueue.size==1的时候才执行?

### ISSUE THREAD

**Issue by kahzix** [Liam6666/FragmentationX#10]
f (actionQueue.size() == 1){
            handler.post(new Runnable() {
                @Override
                public void run() {
                    Action a = actionQueue.peek();
                    if (a != null){
                        long duration = a.run();
                        handler.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                actionQueue.clear();
                            }
                        },duration);

**Comment by Liam6666** [comment]
设计之初本意是避开乱入栈导致的不稳定，目前已经发现这个漏洞
FragmentationX 正在全面优化，请耐心等待
感谢提问

**Comment by kahzix** [comment]
但是如果这样的话，我担心monkey click，导致actionQueue添加多个Action，那么队列岂不是无法执行了

**Comment by Liam6666** [comment]
乱入栈出栈动画也会错乱的，参考一下Fragmentation，也是做了限制

**Comment by kahzix** [comment]
这个我知道，我的疑问是，如何保证actionQueue只有一个对象，而非多个

**Comment by kahzix** [comment]
如果不能保证actionQueue只有一个对象，一旦出现多个的时候，那么所有的fragment岂不是无法执行。我看了fragmentation的代码，好像并没有做这方面的处理，也可能处理了，我没看明白，所以请教一下。

**Comment by Liam6666** [comment]
当前有事物在执行的时候，删掉了其他任务，并且不再加入新任务
