### ISSUE TITLE
请问isThrottleBACK的意思是什么，在什么场景下会出现

### ISSUE THREAD

**Issue by kahzix** [Liam6666/FragmentationX#11]
private boolean isThrottleBACK(Action action) {
        if (action.action == Action.ACTION_BACK) {
            Action head = mQueue.peek();
            if (head != null && head.action == Action.ACTION_POP) {
                return true;
            }
        }
        return false;
    }
}

**Comment by Liam6666** [comment]
没有这行代码

**Comment by kahzix** [comment]
public class ActionQueue {
    public static final String TAG = "ActionQueue";
    private Queue<Action> mQueue = new LinkedList<>();
    private Handler mMainHandler;

    public ActionQueue(Handler mainHandler) {
        this.mMainHandler = mainHandler;
    }

    public void enqueue(final Action action) {
        if (isThrottleBACK(action)){//  如果重复后退 则不处理
            Log.i(TAG,"isThrottleBACK...");
            return;
        }

        if (action.action == Action.ACTION_LOAD && mQueue.isEmpty()
                && Thread.currentThread() == Looper.getMainLooper().getThread()) {
            action.run();
            return;
        }

        mMainHandler.post(new Runnable() {
            @Override
            public void run() {
                enqueueAction(action);
            }
        });
    }
这个是Fragmentation的代码  没看懂  所以请教一下

**Comment by Liam6666** [comment]
防止快速后退，动画卡顿
