### ISSUE TITLE
单activity+多个fragment，frafment中有tablayout和viewPager2的问题

### ISSUE THREAD

**Issue by mabaixiao** [Liam6666/FragmentationX#12]
请问单activity+多个fragment，frafment中有tabLayout和viewPager2，当切换fragment时，在重新返回之前的fragment，viewpager2就不显示了，请问如果使用当前库的话，应该怎么操作？

**Comment by mabaixiao** [comment]
解决了，把getFragmentManager()改为getChildFragmentManager()就可以了。。

**Comment by Liam6666** [comment]
加油……
